project_id = "oxaghzctrjemldcezcqq"

[functions.verify-paystack-payment]

[functions.send-notification-email]

[functions.generate-job-recommendations]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false
