import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export interface Reservation {
  id: string;
  booking_reference: string;
  business_id: string;
  user_id: string | null;
  guest_name: string;
  guest_email: string;
  guest_phone: string | null;
  reservation_date: string;
  reservation_time: string;
  party_size: number;
  table_preference: string | null;
  occasion: string | null;
  status: string;
  special_requests: string | null;
  confirmed_at: string | null;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  created_at: string;
  updated_at: string;
  businesses?: {
    id: string;
    name: string;
    image_url: string | null;
    address: string | null;
    phone: string | null;
  };
}

export function useUserReservations() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["user-reservations", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("restaurant_reservations")
        .select(`
          *,
          businesses:business_id (
            id,
            name,
            image_url,
            address,
            phone
          )
        `)
        .order("reservation_date", { ascending: false });

      if (error) throw error;
      return data as Reservation[];
    },
    enabled: !!user?.id,
  });
}

export function useBusinessReservations(businessId: string) {
  return useQuery({
    queryKey: ["business-reservations", businessId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("restaurant_reservations")
        .select("*")
        .eq("business_id", businessId)
        .order("reservation_date", { ascending: true })
        .order("reservation_time", { ascending: true });

      if (error) throw error;
      return data as Reservation[];
    },
    enabled: !!businessId,
  });
}

export function useReservationMutations() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  const createReservation = useMutation({
    mutationFn: async (reservation: {
      business_id: string;
      guest_name: string;
      guest_email: string;
      guest_phone?: string;
      reservation_date: string;
      reservation_time: string;
      party_size: number;
      table_preference?: string;
      occasion?: string;
      special_requests?: string;
    }) => {
      const { data, error } = await supabase
        .from("restaurant_reservations")
        .insert({
          ...reservation,
          user_id: user?.id || null,
          booking_reference: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["user-reservations"] });
      queryClient.invalidateQueries({ queryKey: ["business-reservations", data.business_id] });
      toast.success("Reservation submitted successfully!");
    },
    onError: (error) => {
      toast.error("Failed to create reservation");
      console.error(error);
    },
  });

  const cancelReservation = useMutation({
    mutationFn: async ({ id, reason }: { id: string; reason?: string }) => {
      const { data, error } = await supabase
        .from("restaurant_reservations")
        .update({
          status: "cancelled",
          cancelled_at: new Date().toISOString(),
          cancellation_reason: reason || null,
        })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["user-reservations"] });
      queryClient.invalidateQueries({ queryKey: ["business-reservations", data.business_id] });
      toast.success("Reservation cancelled");
    },
    onError: (error) => {
      toast.error("Failed to cancel reservation");
      console.error(error);
    },
  });

  const updateReservationStatus = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: string }) => {
      const updates: Record<string, unknown> = { status };
      if (status === "confirmed") {
        updates.confirmed_at = new Date().toISOString();
      }

      const { data, error } = await supabase
        .from("restaurant_reservations")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["user-reservations"] });
      queryClient.invalidateQueries({ queryKey: ["business-reservations", data.business_id] });
      toast.success(`Reservation ${data.status}`);
    },
    onError: (error) => {
      toast.error("Failed to update reservation");
      console.error(error);
    },
  });

  return { createReservation, cancelReservation, updateReservationStatus };
}
