-- Add Sports & Recreation category
INSERT INTO public.business_categories (name, icon, description) VALUES
  ('Sports & Recreation', 'Trophy', 'Golf clubs, sports centers, and leisure facilities');

-- Add Golf Clubs across Ghana
INSERT INTO public.businesses (
  name, 
  description, 
  category, 
  region, 
  address,
  phone,
  email,
  website,
  rating,
  review_count,
  is_verified,
  is_featured,
  latitude,
  longitude
) VALUES
  (
    'Celebrity Golf Club',
    'Premier 18-hole championship golf course in Sakumono. Features world-class facilities including a clubhouse, pro shop, and training academy. Host to numerous regional tournaments and offering memberships for golf enthusiasts.',
    'Sports & Recreation',
    'Greater Accra',
    'Sakumono Estate, Tema Motorway, Accra',
    '+233 30 230 1234',
    'info@celebritygolfclub.com.gh',
    'https://celebritygolfclub.com.gh',
    4.8,
    87,
    true,
    true,
    5.6297,
    -0.0945
  ),
  (
    'Achimota Golf Club',
    'Historic golf club established in 1932, featuring a challenging 18-hole course. Rich in tradition with colonial architecture, elegant clubhouse, and professional coaching services. One of Ghana''s oldest and most prestigious golf clubs.',
    'Sports & Recreation',
    'Greater Accra',
    'Achimota, Off Nsawam Road, Accra',
    '+233 30 240 5678',
    'secretary@achiomotagolf.com',
    'https://achiomotagolf.com',
    4.7,
    102,
    true,
    true,
    5.6892,
    -0.2234
  ),
  (
    'Royal Golf Club Kumasi',
    '18-hole championship golf course in the heart of Ashanti Region. Modern club house with restaurant and bar facilities, golf cart rentals, and professional instruction. Beautiful landscape with mature trees and water features.',
    'Sports & Recreation',
    'Ashanti',
    'Ridge Area, Kumasi',
    '+233 32 202 3456',
    'info@royalgolfkumasi.com',
    'https://royalgolfkumasi.com',
    4.6,
    65,
    true,
    true,
    6.6885,
    -1.6244
  ),
  (
    'Takoradi Golf Club',
    'Coastal golf experience with stunning ocean views. 18-hole course designed to challenge players of all skill levels. Features include a well-maintained practice range, clubhouse with ocean terrace, and equipment rental services.',
    'Sports & Recreation',
    'Western',
    'Airport Ridge, Takoradi',
    '+233 31 202 7890',
    'info@takoradigolf.com',
    'https://takoradigolf.com',
    4.5,
    48,
    true,
    false,
    4.8967,
    -1.7543
  ),
  (
    'Tema Golf Club',
    'Family-friendly 9-hole golf course perfect for beginners and casual players. Welcoming atmosphere with affordable green fees, equipment rental, and basic coaching. Popular weekend destination for families and corporate events.',
    'Sports & Recreation',
    'Greater Accra',
    'Community 7, Tema',
    '+233 30 330 4567',
    'temagolfclub@gmail.com',
    NULL,
    4.4,
    56,
    false,
    false,
    5.6699,
    -0.0166
  ),
  (
    'Damang Golf Club',
    'Mining community golf club offering a peaceful 9-hole course surrounded by natural vegetation. Well-maintained greens and fairways, clubhouse with refreshment facilities. Popular among local mining executives and expatriates.',
    'Sports & Recreation',
    'Western',
    'Damang Mining Area, Wassa',
    '+233 31 202 5432',
    'damang.golf@goldfields.com',
    NULL,
    4.3,
    34,
    false,
    false,
    5.8234,
    -2.0876
  ),
  (
    'La Palm Royal Beach Hotel Golf Course',
    'Exclusive resort golf course offering stunning beachfront views. 9-hole executive course ideal for hotel guests and members. Features include golf cart service, club rental, and access to hotel amenities including spa and restaurants.',
    'Sports & Recreation',
    'Greater Accra',
    'La Beach Road, La, Accra',
    '+233 30 281 4400',
    'golf@lapalmhotel.com',
    'https://lapalmhotel.com/golf',
    4.6,
    72,
    true,
    false,
    5.5678,
    -0.1455
  ),
  (
    'Obuasi Golf Club',
    'Community golf facility with a well-maintained 9-hole course. Offers affordable membership options and is popular for weekend tournaments. Basic clubhouse facilities with bar and restaurant. Active local golf community.',
    'Sports & Recreation',
    'Ashanti',
    'AngloGold Ashanti Area, Obuasi',
    '+233 32 250 6789',
    'obuasigolf@gmail.com',
    NULL,
    4.2,
    41,
    false,
    false,
    6.2026,
    -1.6711
  ),
  (
    'Labadi Beach Golf Club',
    'Unique coastal golf experience with 9 holes along the beachfront. Challenging wind conditions make for exciting gameplay. Relaxed atmosphere perfect for casual golfers. Clubhouse offers local cuisine and refreshing drinks with sea views.',
    'Sports & Recreation',
    'Greater Accra',
    'Labadi Beach Road, Accra',
    '+233 30 277 8901',
    'info@labadigolf.com',
    NULL,
    4.5,
    38,
    false,
    false,
    5.5712,
    -0.1234
  ),
  (
    'Akosombo Golf Course',
    'Scenic 9-hole golf course overlooking the Volta Lake. Established by VRA, offering spectacular views and challenging terrain. Popular weekend getaway for golf enthusiasts. Basic facilities with clubhouse serving refreshments.',
    'Sports & Recreation',
    'Eastern',
    'Akosombo Township, Near Volta Hotel',
    '+233 24 555 3210',
    'akosombogolf@vra.com',
    NULL,
    4.4,
    29,
    false,
    false,
    6.2667,
    0.0500
  );